services:
  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      DATABASE_NAME: postgres
      DATABASE_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - default

  backend:
    build: .
    working_dir: /app
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
    ports:
      - "8000:8000"
    depends_on:
      - db
      - frontend
    environment:
      DATABASE_HOST: db
      DATABASE_NAME: postgres
      DATABASE_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - default

  frontend:
    build: ./app/frontend
    volumes:
      - static_volume:/app/static/dist
    environment:
      - VITE_API_URL=http://backend:8000
    ports:
      - "5173:5173"
    networks:
      - default

networks:
  default:
    external: true
    name: net

volumes:
  postgres_data:
  static_volume: