# Generated by Django 5.2.7 on 2025-12-20 19:04

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgencyPlanFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Характеристика')),
            ],
            options={
                'verbose_name': 'Характеристика',
                'verbose_name_plural': 'Характеристики',
            },
        ),
        migrations.CreateModel(
            name='CompanyInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200, verbose_name='Компания')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='RU', verbose_name='Телефон')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Обработан')),
            ],
            options={
                'verbose_name': 'Заявка от компании',
                'verbose_name_plural': 'Заявки от компаний',
            },
        ),
        migrations.CreateModel(
            name='AgencyPricingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('subtitle', models.CharField(max_length=50, verbose_name='Подзаголовок')),
                ('price', models.CharField(help_text='₽10,000 /мес', max_length=100, verbose_name='Цена')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('block_type', models.CharField(choices=[('agencies', 'Агентсва'), ('tariffs', 'Тарифы')], max_length=20, verbose_name='Тип блока')),
                ('highlighted', models.BooleanField(default=False, verbose_name='Выдиление')),
                ('features', models.ManyToManyField(blank=True, related_name='plans', to='foragencies.agencyplanfeature')),
            ],
            options={
                'verbose_name': 'Блок тарифов и агенств',
                'verbose_name_plural': 'Блоки тарифов и агенств',
            },
        ),
    ]
